"""empty message

Revision ID: 3ae076a3dd83
Revises: 
Create Date: 2021-01-03 14:16:16.289098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ae076a3dd83'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise', sa.String(length=30), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('exercise_date', sa.Date(), nullable=True),
    sa.Column('rep_1', sa.Integer(), nullable=False),
    sa.Column('rep_2', sa.Integer(), nullable=False),
    sa.Column('rep_3', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exercise', 'exercise_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout')
    # ### end Alembic commands ###
